version: 2
updates:
- package-ecosystem: github-actions
  schedule:
    interval: monthly
- package-ecosystem: npm
  directory: "/report"
  labels:
    - "dependencies"
    # - "javascript"
    - "report"
  schedule:
    interval: monthly
- package-ecosystem: npm
  directory: "/script"
  labels:
    - "dependencies"
    # - "javascript"
    - "script"
  schedule:
    interval: monthly
